@HelloWorldApi_HostAddress = https://localhost:7000

GET {{HelloWorldApi_HostAddress}}/weatherforecast/
Accept: application/json

### Get Hello Message
GET http://localhost:5000/api/Listings

### Get Hello Message
GET https://localhost:7000/api/Listings
