// <auto-generated />
using System;
using HelloWorldApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HelloWorldApi.Migrations
{
    [DbContext(typeof(ListingContext))]
    partial class ListingContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HelloWorldApi.Models.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("HelloWorldApi.Models.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("ListingId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ListingId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("HelloWorldApi.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "House"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Condo"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Townhouse"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Luxury"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Apartment"
                        });
                });

            modelBuilder.Entity("HelloWorldApi.Models.Listing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PostedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SellerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Listings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "142 Oakwood Drive, Austin, TX 78701",
                            CategoryId = 1,
                            Description = "Charming 3-bedroom ranch-style home with an open floor plan, updated kitchen, and a spacious backyard. Perfect for families.",
                            ImageURL = "/images/listings/austin-ranch.jpeg",
                            PostedDate = new DateTime(2025, 1, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Price = 324900m,
                            SellerName = "James Carter"
                        },
                        new
                        {
                            Id = 2,
                            Address = "87 Maple Street, Denver, CO 80203",
                            CategoryId = 2,
                            Description = "Modern 2-bedroom condo in the heart of downtown Denver. Features floor-to-ceiling windows, granite countertops, and a rooftop terrace.",
                            ImageURL = "/images/listings/denver-condo.jpg",
                            PostedDate = new DateTime(2025, 1, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Price = 415000m,
                            SellerName = "Rachel Thompson"
                        },
                        new
                        {
                            Id = 3,
                            Address = "305 Lakeview Blvd, Orlando, FL 32801",
                            CategoryId = 1,
                            Description = "Stunning 4-bedroom lakefront property with a private dock, screened-in pool, and breathtaking sunset views over Lake Monroe.",
                            ImageURL = "/images/listings/orlando-lakefront.jpg",
                            PostedDate = new DateTime(2025, 2, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Price = 589000m,
                            SellerName = "David Nguyen"
                        },
                        new
                        {
                            Id = 4,
                            Address = "19 Birchwood Lane, Nashville, TN 37201",
                            CategoryId = 3,
                            Description = "Newly built 3-bedroom townhouse in a quiet suburban neighborhood. Open-concept living area, two-car garage, and energy-efficient appliances.",
                            ImageURL = "/images/listings/nashville-townhouse.jpg",
                            PostedDate = new DateTime(2025, 2, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            Price = 372500m,
                            SellerName = "Monica Harris"
                        },
                        new
                        {
                            Id = 5,
                            Address = "560 Sunset Avenue, Phoenix, AZ 85001",
                            CategoryId = 4,
                            Description = "Elegant 5-bedroom luxury home with a resort-style pool, outdoor kitchen, and mountain views. Located in a gated community.",
                            ImageURL = "/images/listings/phoenix-luxury.jpg",
                            PostedDate = new DateTime(2025, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Price = 8750000m,
                            SellerName = "Steven Alvarez"
                        },
                        new
                        {
                            Id = 6,
                            Address = "233 Elm Court, Charlotte, NC 28201",
                            CategoryId = 1,
                            Description = "Cozy 2-bedroom starter home with a newly renovated bathroom, hardwood floors throughout, and a large front porch.",
                            ImageURL = "/images/listings/charlotte-starter.jpg",
                            PostedDate = new DateTime(2025, 3, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Price = 218000m,
                            SellerName = "Angela Foster"
                        },
                        new
                        {
                            Id = 7,
                            Address = "48 River Run Road, Portland, OR 97201",
                            CategoryId = 5,
                            Description = "Charming studio apartment steps from the Willamette River. Features exposed brick walls, updated fixtures, and in-unit laundry.",
                            ImageURL = "/images/listings/portland-studio.jpg",
                            PostedDate = new DateTime(2025, 3, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Price = 189000m,
                            SellerName = "Brian Okafor"
                        },
                        new
                        {
                            Id = 8,
                            Address = "791 Pinecrest Way, Atlanta, GA 30301",
                            CategoryId = 1,
                            Description = "Spacious 4-bedroom colonial home on a half-acre lot. Features a finished basement, chef's kitchen, and a large wraparound deck.",
                            ImageURL = "/images/listings/atlanta-colonial.jpg",
                            PostedDate = new DateTime(2025, 4, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Price = 495000m,
                            SellerName = "Karen Mitchell"
                        });
                });

            modelBuilder.Entity("HelloWorldApi.Models.CartItem", b =>
                {
                    b.HasOne("HelloWorldApi.Models.Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HelloWorldApi.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HelloWorldApi.Models.Listing", "Listing")
                        .WithMany()
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Category");

                    b.Navigation("Listing");
                });

            modelBuilder.Entity("HelloWorldApi.Models.Listing", b =>
                {
                    b.HasOne("HelloWorldApi.Models.Category", "Category")
                        .WithMany("Listings")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("HelloWorldApi.Models.Cart", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("HelloWorldApi.Models.Category", b =>
                {
                    b.Navigation("Listings");
                });
#pragma warning restore 612, 618
        }
    }
}
